### ISSUE TITLE
This project still alive?

### ISSUE THREAD

**Issue by bergpb** [billimek/prometheus-speedtest-exporter#5]
I'm used this project to get information about my internet running in my home, I'm running a more updated version and I really appreciate If I can contribute with this project to be used for me and another users.
But I saw a opened PR from two years ago and not be merged and due that I'm asking if this project still alive?

**Comment by billimek** [comment]
Hi @bergpb - I blame getting too many notifications from github and this getting lost in that noise.  The old PR is merged now.  I've been using https://github.com/MiguelNdeCarvalho/speedtest-exporter in my personal cluster for a while now and think I forgot about this project.
